### ISSUE TITLE
make_db.py breaks when pk_detect = False

### ISSUE THREAD

**Issue by shenglan0407** [dermen/loki#1]
Line 335 in make_db.py

> self.df = pandas.DataFrame(self.df_dict)
> fails when pk_pos is given a value and pk_detect set to False.
> Following error is raised.
> ValueError('arrays must all be same length')

I think it's because peak detection related entries in self.df_dict have length zero.

**Comment by dermen** [comment]
if you fixed this locally can you push ?

**Comment by dermen** [comment]
I went ahead and fixed this in the last commit...
